version: '3'

services:
  postgres:
    image: postgis/postgis:13-3.3  # ✅ Use PostGIS-enabled PostgreSQL image
    container_name: postgres_df
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_df
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - airflow_network

networks:
  airflow_network:
    external: false
